---
version: "3.7"
services:
  myapp-frontend:
    build:
      context: ./frontend
    image: dockerakshay1985/myapp-frontend:1.0
    environment:
        BACKENDLB: myapp-backend
    ports:
        - "9000:80"
    volumes:
      - type: volume
        source: myapp-frontend-logvol
        target: /var/log
    depends_on:
      - myapp-backend
  myapp-frontend-logs:
    build:
      context: ./awslogs
    image: dockerakshay1985/myapp-frontend-logs:1.0
    volumes:
      - type: volume
        source: myapp-frontend-logvol
        target: /mnt/log
        read_only: true
    depends_on:
      - myapp-frontend
  myapp-backend:
    build:
      context: ./backend
    image: dockerakshay1985/myapp-backend:1.0
    volumes:
      - type: volume
        source: myapp-backend-logvol
        target: /var/log
  myapp-backend-logs:
    build:
      context: ./awslogs
    image: dockerakshay1985/myapp-backend-logs:1.0
    volumes:
      - type: volume
        source: myapp-backend-logvol
        target: /mnt/log
        read_only: true
    depends_on:
      - myapp-backend
volumes:
    myapp-frontend-logvol:
    myapp-backend-logvol: