---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mycartlatest-frontend
  namespace: mycartlatest
spec:
  minReadySeconds: 5
  selector:
    matchLabels:
      app: mycartlatest
      layer: frontend
  replicas: 2
  revisionHistoryLimit: 5
  template: 
    metadata:
      labels:
        app: mycartlatest
        layer: frontend
    spec:
      containers:
      - name: mycartlatest-frontend-container
        image: dockerakshay1985/myapp-frontend:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "0.5"
            memory: "200Mi"
